
spring:
  application:
    name: netty-chat
  redis:
    host: 127.0.0.1
    port: 6379
    database: 0
    lettuce:
      pool:
        max-wait: -1
        max-idle: 8
        max-active: 8
        min-idle: 0
    timeout: 10000
  security:
    user:
      password: admin
      name: 1234567

  rabbitmq:
    host: test.rabbitmq01.yktour.com.cn
    port: 5672
    username: rabbit
    password: MQ7788%%
    publisher-confirms: true
    publisher-returns: true
    virtual-host: /
    listener:
      direct:
        acknowledge-mode: manual
      simple:
        acknowledge-mode: manual

server:
  servlet:
    context-path: /chat
  port: 5601

netty:
  port: 5602
  bossThread: 2
  workerThread: 2
  keepalive: true
  backlog: 100

http:
  pool:
    max-totle: 200
    max-per-route: 20
    connect-request-timeout: 5000
    connect-timeout: 5000
    socket-timeout: 61000





